INSERT INTO candidates (id, name, experience_years, skills) VALUES (1, 'Aryanna Paucek-Frami', 3, '["Six Sigma","Team Leadership","Budgeting","Lean Manufacturing","Waste Management"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (1, 7, 4, 2, 'Sum adipiscor admoneo adulatio speciosus.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (2, 'Sigrid Kreiger V', 2, '["Process Optimization","Six Sigma","Waste Management","Lean Manufacturing","Supply Chain"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (2, 4, 4, 6, 'Tabgo certe balbus cohors.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (3, 'Jacqueline Jacobson', 13, '["Supply Chain","Process Optimization"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (3, 2, 6, 6, 'Comminor defungo officiis testimonium volaticus repellat cruentus vulticulus.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (4, 'Brent Klocko', 10, '["Lean Manufacturing","Supply Chain","Process Optimization","Team Leadership","Budgeting"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (4, 1, 6, 8, 'Cursim amplitudo sumo pauci antepono sed non delibero.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (5, 'Shirley Durgan Sr.', 6, '["OSHA Certified","Supply Chain","Process Optimization","Waste Management"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (5, 5, 4, 7, 'Umbra sumo utor ter labore cito.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (6, 'Eva Koepp DDS', 14, '["Budgeting","Lean Manufacturing","OSHA Certified","Process Optimization"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (6, 4, 6, 8, 'Allatus occaecati modi velit.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (7, 'Lilliana Gulgowski', 11, '["Supply Chain","Budgeting","Process Optimization","Six Sigma"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (7, 3, 10, 5, 'Victus tantillus tribuo tamen tremo.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (8, 'Harry Grady', 14, '["OSHA Certified","Waste Management","Six Sigma","Team Leadership"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (8, 5, 2, 6, 'Voluptas admitto aduro subvenio tertius valde demo deprimo recusandae.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (9, 'Scot Rogahn', 2, '["Process Optimization","Lean Manufacturing","Six Sigma","Supply Chain","Budgeting"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (9, 2, 4, 4, 'Molestias subiungo constans.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (10, 'Rodolfo Harber PhD', 12, '["Supply Chain","Process Optimization","Six Sigma"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (10, 3, 9, 5, 'Centum alias anser ubi avarus volva attero sumptus.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (11, 'Latoya Zboncak', 10, '["Team Leadership","Lean Manufacturing","Waste Management","Process Optimization"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (11, 8, 8, 9, 'Aveho doloremque patrocinor urbanus degenero.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (12, 'Friedrich Hahn-Bednar', 18, '["Six Sigma","Budgeting"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (12, 3, 10, 8, 'Universe in infit impedit bardus timidus tum capto.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (13, 'Melanie Heaney', 16, '["Six Sigma","Team Leadership","Process Optimization"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (13, 2, 3, 9, 'Valens combibo distinctio custodia sono defluo debeo cunctatio ulciscor somnus.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (14, 'Miss Betty Mayert', 3, '["Supply Chain","Six Sigma","Waste Management","OSHA Certified","Lean Manufacturing"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (14, 4, 2, 2, 'Cado ulciscor placeat ocer.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (15, 'Gerald Quigley', 7, '["Team Leadership","Six Sigma","Waste Management","Supply Chain"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (15, 7, 6, 2, 'Sapiente thesis recusandae.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (16, 'Monica Fisher', 5, '["Process Optimization","Team Leadership","OSHA Certified","Budgeting"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (16, 10, 1, 1, 'Degenero absum magni aer coma tutamen virga desidero usus.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (17, 'Cleveland Conn', 12, '["Supply Chain","Lean Manufacturing","Budgeting","Team Leadership"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (17, 5, 6, 9, 'Officiis repellat ceno totidem cupiditas animi vita.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (18, 'Kerry McDermott', 6, '["Six Sigma","Team Leadership","Lean Manufacturing","Process Optimization","Budgeting"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (18, 6, 5, 4, 'Atavus abduco attollo deserunt surculus brevis acceptus soleo abscido occaecati.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (19, 'Ricky Gorczany', 19, '["Six Sigma","Team Leadership","Process Optimization","Waste Management"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (19, 4, 2, 6, 'Vulnero auctor deduco paulatim.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (20, 'Alexandrea Herman', 9, '["OSHA Certified","Waste Management"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (20, 2, 7, 2, 'Acceptus caste amita.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (21, 'Camille Dach', 14, '["Supply Chain","OSHA Certified","Team Leadership","Budgeting","Process Optimization"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (21, 1, 1, 7, 'Cur calcar capio volaticus vigilo solitudo triumphus toties cicuta coma.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (22, 'Camren Kunde', 4, '["Six Sigma","Budgeting"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (22, 5, 4, 7, 'Dignissimos decet vomito vergo statua comis adflicto.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (23, 'Kelvin Hickle', 6, '["OSHA Certified","Waste Management","Supply Chain","Lean Manufacturing","Process Optimization"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (23, 5, 2, 5, 'Deputo suppono vestigium officiis culpa suscipio valde uterque toties.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (24, 'Dr. Quentin Will', 15, '["Supply Chain","Budgeting","Six Sigma","Lean Manufacturing"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (24, 9, 5, 7, 'Tenetur curis ait tempora atque votum via aestus cursus.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (25, 'Gustavo Rippin', 18, '["Lean Manufacturing","Budgeting","Process Optimization"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (25, 9, 6, 1, 'Denuo demum voluptatem decretum convoco.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (26, 'Belle Armstrong', 3, '["Lean Manufacturing","Process Optimization","Team Leadership"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (26, 2, 2, 7, 'Totidem eaque stultus.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (27, 'Carole Cronin', 4, '["Supply Chain","OSHA Certified","Waste Management","Budgeting"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (27, 2, 5, 1, 'Colligo cohaero delectus depono ullus vado repellat talis argentum.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (28, 'Regina Doyle', 13, '["Supply Chain","OSHA Certified","Process Optimization","Six Sigma"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (28, 1, 6, 7, 'Aeneus cattus decretum bestia speciosus verumtamen claro vacuus contigo.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (29, 'Michelle Durgan-Stokes', 13, '["Lean Manufacturing","Process Optimization"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (29, 6, 5, 9, 'Studio adhuc conduco alienus decerno vinitor undique denuo utroque curia.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (30, 'Clara Collins', 15, '["Budgeting","Supply Chain","Waste Management","Lean Manufacturing"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (30, 10, 7, 10, 'Spes natus vilitas comparo.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (31, 'Dr. Scott Reynolds', 11, '["Lean Manufacturing","OSHA Certified"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (31, 2, 5, 7, 'Coniecto adicio utrimque curto.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (32, 'Gloria Murphy', 8, '["OSHA Certified","Supply Chain","Budgeting"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (32, 5, 8, 2, 'Urbanus tutamen stabilis acceptus.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (33, 'Russel Satterfield', 9, '["Supply Chain","Waste Management"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (33, 3, 9, 3, 'Adipiscor territo turpis vulticulus thermae desidero harum accusamus apostolus totam.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (34, 'Dr. Anne Bashirian', 13, '["Supply Chain","Team Leadership","Lean Manufacturing","Process Optimization","Waste Management"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (34, 4, 2, 6, 'Corporis conor iure delectatio depereo thema copiose cavus.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (35, 'Melvin Mraz', 4, '["Process Optimization","Budgeting","Waste Management","Lean Manufacturing"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (35, 9, 2, 8, 'Creptio corroboro una abscido tremo cavus.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (36, 'Kevon Murray', 11, '["Process Optimization","OSHA Certified","Supply Chain","Lean Manufacturing"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (36, 4, 10, 1, 'Aggero adhaero ambitus despecto sollicito terreo dolore crebro eaque vulgo.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (37, 'Dominic Walsh', 13, '["Lean Manufacturing","OSHA Certified","Six Sigma","Budgeting"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (37, 6, 10, 5, 'Casso expedita provident vociferor titulus nam modi bis modi aggero.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (38, 'Landen Block-Harber', 7, '["Supply Chain","Team Leadership","Process Optimization","OSHA Certified"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (38, 2, 5, 8, 'Aetas catena aperiam tergiversatio caelestis deorsum.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (39, 'Barbara Barrows', 16, '["Waste Management","Team Leadership"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (39, 2, 6, 2, 'Vorago cupressus adaugeo culpa molestiae sonitus timidus ago.');
INSERT INTO candidates (id, name, experience_years, skills) VALUES (40, 'Melany Schaefer', 4, '["Supply Chain","Budgeting","Six Sigma"]');
INSERT INTO evaluations (candidate_id, crisis_management_score, sustainability_score, team_motivation_score, comments) VALUES (40, 3, 6, 6, 'Vociferor vomito nulla amet.');
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (30, 27, 1);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (11, 25, 2);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (12, 21, 3);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (24, 21, 4);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (37, 21, 5);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (17, 20, 6);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (29, 20, 7);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (35, 19, 8);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (6, 18, 9);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (7, 18, 10);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (10, 17, 11);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (5, 16, 12);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (22, 16, 13);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (25, 16, 14);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (4, 15, 15);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (15, 15, 16);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (18, 15, 17);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (32, 15, 18);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (33, 15, 19);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (36, 15, 20);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (38, 15, 21);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (40, 15, 22);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (2, 14, 23);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (3, 14, 24);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (13, 14, 25);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (28, 14, 26);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (31, 14, 27);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (1, 13, 28);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (8, 13, 29);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (16, 12, 30);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (19, 12, 31);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (23, 12, 32);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (34, 12, 33);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (20, 11, 34);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (26, 11, 35);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (9, 10, 36);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (39, 10, 37);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (21, 9, 38);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (14, 8, 39);
INSERT INTO rankings (candidate_id, total_score, current_rank) VALUES (27, 8, 40);